### ISSUE TITLE
Table ronde #8

### ISSUE THREAD

**Issue by kud** [TablesRondes/tables-rondes#52]
Hello,

Pour ce nouvel épisode, nous cherchons un sujet. Si vous avez une idée, n'hésitez pas à proposer. ;)

---

# Sujets

## Comment communiquer en entreprise avec des personnes non techniques

En gros, éviter les frictions, les mauvaises compréhensions, quel outil utiliser pour communiquer, être réactif par rapport à un besoin, comment convaincre quelqu'un de non technique de faire ce qu'on souhaite faire (souvent à coup d'arguments sur l'argent d'ailleurs :D)

## Réécrire une bibliothèque et comprendre les principes

on choisit une bibliothèque ultra commune et relativement minimale pour pas y passer 3 plombes non plus, (e.g. EventEmitter, jQuery, async, lodash, bluebird, backbone) et on se partage une machine pour en coder l'équivalent, avec de nouvelles approches et de nouvelles idées.

**Comment by kud** [comment]
Ca peut être une continuation sur la table ronde #7 qui à mon sens n'était pas finie.

Sinon, ça peut être une table ronde sur vos problèmes dans votre entreprise pour savoir comment les résoudre.

Ou sinon vous vous ramenez avec un problème de code et on le résout.

**Comment by kud** [comment]
Le principe de table-ronde / bar dans une entreprise me plait bien aussi dans l'idée si on n'a aucun sujet. Les sujets arrivent d'eux-même en général.

**Comment by risseraka** [comment]
Je peux peut-être proposer un truc dans les nouveaux locaux de Captain Dash.
On déménage demain, j'aurais plus d'infos d'ici là.

**Comment by kud** [comment]
Okay merci. ;)

**Comment by bloodyowl** [comment]
idée:

on choisit une bibliothèque ultra commune et relativement minimale pour pas y passer 3 plombes non plus, (e.g. EventEmitter, jQuery, async, lodash, bluebird, backbone) et on se partage une machine pour en coder l'équivalent, avec de nouvelles approches et de nouvelles idées.

vous en pensez quoi ?

**Comment by risseraka** [comment]
Très bonne idée.

Du X-programming où X > 2 !

ServerSentEvent ?

**Comment by kud** [comment]
Je propose un sujet (qui n'est pas forcément pour la table 8) : 

> Comment communiquer en entreprise avec des personnes non techniques

En gros, éviter les frictions, les mauvaises compréhensions, quel outil utiliser pour communiquer, être réactif par rapport à un besoin, comment convaincre quelqu'un de non technique de faire ce qu'on souhaite faire (souvent à coup d'arguments sur l'argent d'ailleurs :D)

**Comment by kud** [comment]
> dialogue = di = deux, c'est quoi un dialogue à > 2 ?

Intéressant, à définir oui.

**Comment by arnaudlimbourg** [comment]
J'aime bien le sujet de @kud (pas forcément pour la prochaine table)

**Comment by kud** [comment]
Merci @arnaudlimbourg. Je note tout ça en premier commentaire.

**Comment by kud** [comment]
A ce sujet, je ne suis pas contre avoir un médiateur durant la session. Je veux bien me proposer, sauf si cela gène, et je laisse volontiers ma place, mais j'aimerais tout de même une gestion du dialogue dans un premier temps. Et une anarchie totale en deuxième partie si des personnes le souhaitent soit en deuxième temps dans la table ronde soit dans un bar à côté, etc.

**Comment by bloodyowl** [comment]
pas forcément besoin, je pense juste qu'il faille faire des slides intercalaires pour structurer les premiers dialogues autour des sujets prévus, nan?

**Comment by kud** [comment]
+1 pour les slides mais aussi +1 pour donner un minimum la parole à quelqu'un dans un temps raisonnable.

**Comment by MattiSG** [comment]
On peut avoir un bâton de parole pour éviter d'avoir un médiateur qui ne peut pas participer. Et @kud frappe les gens qui ne respectent pas le bâton de parole  :)

**Comment by bloodyowl** [comment]
wai non je pense pas que ce soit sain d'aller jusqu'au bâton de parole

**Comment by MattiSG** [comment]
@bloodyowl Tu en ressens peut-être moins le besoin car c'est le plus souvent toi qui gagne au jeu de qui parle le plus fort ?  :)

**Comment by bloodyowl** [comment]
lol non, juste qu'une discussion trop cadrée c'est pas spontané et ça réduit les échanges ; or le principe même des tables rondes c'est justement l'échange informel et spontané.

**Comment by kud** [comment]
Y'a "trop cadrée" et "donner la parole".

**Comment by dlamoureux** [comment]
Sujet possible : la gestion des events "pointer" selon les devices.
Click vs tap ?
Fast click ?
Fake stretch / double Tap / Support ?
Browser / Device detection ?
Bonnes pratiques / astuces / retours d'expérience.

@MattiSG @bloodyowl Le baton ne me semble pas être une mauvaise idée si bière il y a :)

**Comment by risseraka** [comment]
Sujet : le freelance.
- les avantages;
- les risques;
- Obi-Wan Kenobi.

**Comment by clementgalidie** [comment]
Hello,
> idée:
on choisit une bibliothèque ultra commune et relativement minimale pour pas y passer 3 plombes non plus, (e.g. EventEmitter, jQuery, async, lodash, bluebird, backbone) et on se partage une machine pour en coder l'équivalent, avec de nouvelles approches et de nouvelles idées.
vous en pensez quoi ?
> – bloodyowl

Ça semble pas mal : on va pouvoir coder un peu (beaucoup ? :grinning:), recevoir et/ou donner des conseils tout en discutant (idéalement du sujet choisi hein, pas comme lors de la table ronde sur les build tools).

Vis-à-vis du bâton de parole, franchement, y a – j'espère – largement moyen de s'auto-gérer.

**Comment by dlamoureux** [comment]
Et sinon, on fait ça quand ?

**Comment by kud** [comment]
On a pas encore défini le sujet il me semble ? Il y a eu plusieurs propositions. Par lequel voulez-vous commencer ?

**Comment by risseraka** [comment]
Autre sujet : les écueils psychologiques du programmeur.
- trop réfléchir vs ne pas assez réfléchir;
- l'optimisation prématurée;
- la psychorigidité du développeur face à son propre code.
Un peu de branlette intellectuelle, ça vous dit ?

**Comment by bloodyowl** [comment]
**BON ON VOTE?**

**Comment by risseraka** [comment]
Je vote et je dis qu'il bluff. :trollface:
Sinon j'aimais bien ton idée Mat', (je peux t'appeler Mat' ?)

**Comment by bloodyowl** [comment]
stu mets 2 t :+1:

**Comment by MattiSG** [comment]
Ça va être pratique…  ;)

**Comment by kud** [comment]
Sinon les mentions, c'est pas mal comme principe.

**Comment by kud** [comment]
Moi l'idée de @bloodyowl peut être sympa mais je déteste je l'avoue le pair programming.

**Comment by bloodyowl** [comment]
bon, ce que je vous propose c'est qu'on fasse ce live-coding pour cette edition et qu'on se refasse une edition fin juillet/début aout sur un des sujets proposés.

je peux host l'event à mon taf, allez juste me donner les dates qui vous vont sur doodle: http://doodle.com/3qsi6yftsgz3685k

poke @kud @risseraka @skinnyfoetusboy @arnaudlimbourg @MattiSG @dlamoureux @clementgalidie @Freddy03h @remitbri @AntoinePlu @revolunet @bobylito

**Comment by risseraka** [comment]
A voté.

**Comment by revolunet** [comment]
sur le principe de se partager une machine, à tester, mais je suis pas à l'aise sur VIM :)

**Comment by kud** [comment]
Indisponible. ;)

**Comment by bloodyowl** [comment]
tkt @revolunet on mettra atom

**Comment by bloodyowl** [comment]
bon, nouvelles dates: http://doodle.com/polls/notifications?participantId=554826163&pollId=2maf65qcziaa6csc&adminKey=ctn2fhwq

**Comment by bloodyowl** [comment]
vous seriez chauds pour demain ?

**Comment by risseraka** [comment]
Pas possible pour moi, un autre meetup de prévu.

On Wed, Jul 15, 2015 at 9:55 AM, Matthias Le Brun <notifications@github.com>
wrote:

> vous seriez chauds pour demain ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/tables-rondes/issues/52#issuecomment-121521394>
> .
>



-- 
Adrien Risser,
Freelance Node.js Consultant
M. +33 6 59 60 32 58

**Comment by MattiSG** [comment]
Sans moi.

**Comment by kud** [comment]
Indispo.

**Comment by arnaudlimbourg** [comment]
Pas possible

**Comment by clementgalidie** [comment]
Pas possible non plus de mon côté.

**Comment by revolunet** [comment]
Hello, Bonne année à tous :)

Un sujet qui me taraude en ce moment, et que j'ai du mal à poser par écrit : Comment distribuer des composants react riches dans des environnement hétérogènes ?

Le problème: on créé des composants riches, et s'ils utilisent flux, notamment dans des sous-composants nestés, alors ils ne sont plus importables directement avec des props, a moins de passer toutes les props des parents vers les childs

Ex:
```html
<CardVideo src={src} playlist={playlistItems}>
    <Player src={src}/>
    <Playlist items={playlistItems}>
            <PlaylistItem>
                    <Share website="http://putaindecode.io" item={item}>
            <PlaylistItem>
    </Playlist>
</CardVideo>
```

Comment distribuer ce composant pour qu'il soit utilisable/configurable dans un autre env ?

Par exemple, comment faire pour utiliser un tel composant dans des environnements flux différents ?

Quelles autres stratégies possibles que passer toutes les props des parents aux child ?

**Comment by bloodyowl** [comment]
closing in favour of #54
