### ISSUE TITLE
Kind of outdated and not "supported" officially by putaindecode

### ISSUE THREAD

**Issue by MoOx** [TablesRondes/tables-rondes#53]
Should this repo go await?
Maybe you should create an org?

**Comment by kud** [comment]
I think we'll do it ourselves with @bloodyowl if needed. No need to be supported by putaindecode indeed.

**Comment by MoOx** [comment]
Please go to settings, first page, at the bottom then transfert it to yourself or a new organisation, otherwise I need to transfert to me, then to you or your new orga.

**Comment by bloodyowl** [comment]
@kud should we create a new org?

**Comment by kud** [comment]
@bloodyowl depends also on you. If you're still interested by the idea (I am), yes. :)

**Comment by bloodyowl** [comment]
I am :smile:

**Comment by kud** [comment]
Let's do it so.

**Comment by bloodyowl** [comment]
done
