### ISSUE TITLE
JavaScript fatigue

### ISSUE THREAD

**Issue by bloodyowl** [TablesRondes/tables-rondes#54]
Je propose ce sujet parce qu'on en parle pas mal en moment:

- Pourquoi les *rants* des développeurs
- Bonnes & mauvaises expériences avec des outils récents (babel, webpack, react, redux, relay … you name it)
- Comment éviter cette *fatigue* sans perdre le nord

**Comment by arnaudlimbourg** [comment]
Bonne idée !

**Comment by kud** [comment]
Je dois être déconnecté, je ne sais guère de quoi on parle quand on parle de _fatigue_ ici. Mais okay pour ce meetup. :)

**Comment by MattiSG** [comment]
:+1:

**Comment by clementgalidie** [comment]
:+1:

**Comment by MattiSG** [comment]
http://www.2ality.com/2016/02/js-fatigue-fatigue.html

**Comment by bloodyowl** [comment]
pour l'endroit est-ce que altima ou numa pourraient host? les deux endroits sont assez centraux.
poke @remitbri @revolunet

sinon on doit pouvoir faire ça à mon taf mais vu que c'est dans le 16 ça risque de faire un peu chier tout le monde :smile:

**Comment by kud** [comment]
L'idéal serait numa.

**Comment by revolunet** [comment]
très bon sujet :) vous êtes bienvenus au DevFloor :)

**Comment by bloodyowl** [comment]
le petit doodle de circonstances http://doodle.com/poll/8pvrh3fzzq8s9xmv

**Comment by risseraka** [comment]
FYI, le 24 c'est Paris.js et le 25 c'est Paris API pour les intéressés.

**Comment by bloodyowl** [comment]
Vraisemblablement ce sera mercredi ou jeudi. Si quelques un d'entre vous ont oublié de remplir le Doodle do it now merci :smile:

**Comment by kud** [comment]
Pas lundi ?

**Comment by bloodyowl** [comment]
vu que @revolunet peut pas lundi c'est exclu :)

**Comment by kud** [comment]
Je me doutais un peu ouais. Bon okay. :)

**Comment by remitbri** [comment]
Je vais me renseigner ce soir pour altima en solution backup.

**Comment by bloodyowl** [comment]
## Update

On fait finalement ça Lundi (merci @remitbri et Altima :smile:)

On se dit 19h30 ?

Pensez bien à vous inscrire ici: https://github.com/TablesRondes/tables-rondes/blob/master/08-JavaScript-Fatigue.md

---

cc @kud @revolunet @risseraka @MattiSG @arnaudlimbourg @Freddy03h @clementgalidie @skinnyfoetusboy @remitbri

**Comment by kud** [comment]
k :)

**Comment by risseraka** [comment]
Ça me tente bien.

**Comment by bloodyowl** [comment]
je ne pourrais pas venir ce soir finalement. pour vous retrouver sur place, vous pouvez ping [remitbri](https://twitter.com/remitbri) en arrivant.

**Comment by kud** [comment]
Je n'ai aucune idée du sujet de base, je viens un peu plus comme spectateur et boire quelques bières avec vous. Si on est tous dans ce cas, ça va être compliqué de débattre, non ?

**Comment by kud** [comment]
Vous voulez maintenir ou on décale ?

**Comment by MattiSG** [comment]
Maintien.

**Comment by risseraka** [comment]
Pauvre @bloodyowl, c'était son sujet tout de même. : '(
Si on change de sujet ça ferait ne pas venir certaines personne ?
Bon après ouvrir un débat 4h30 avant l'event, m'enfin.

**Comment by revolunet** [comment]
Report please ;)

**Comment by revolunet** [comment]
:trollface:

**Comment by remitbri** [comment]
Euh, du coup, c'est reporté ? Maintenu ? Histoire que je redescende pas à l'agence avec @skinnyfoetusboy inutilement…

**Comment by skinnyfoetusboy** [comment]
J'ai créé un strawpoll.
Votez. 
http://strawpoll.me/6889591

**Comment by kud** [comment]
C'est mignon ça. J'ai voté.

**Comment by skinnyfoetusboy** [comment]
<img width="297" alt="capture d ecran 2016-02-22 a 15 55 14" src="https://cloud.githubusercontent.com/assets/5133452/13221640/b745b628-d97c-11e5-9934-7fd39386b52f.png">
Hilarant.

**Comment by kud** [comment]
Qu'est-ce qu'on s'maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarre.

**Comment by remitbri** [comment]
bon bah on reporte à 60%, avec les voix de Tiberi (10 votes sur 8 inscrits)

**Comment by skinnyfoetusboy** [comment]
Bienvenue chez Putain de Code, on fait voter les morts !

**Comment by Freddy03h** [comment]
Je suis pour reporter !

**Comment by skinnyfoetusboy** [comment]
Dix-sept votes, vous êtes de grands malades.

**Comment by risseraka** [comment]
Y a au moins 10 votes en trop, ça fait donc 7 voies OUI, 0 voies NON.

**Comment by remitbri** [comment]
ce sont des voies sans issue…

**Comment by risseraka** [comment]
Je ne vois pas de quoi tu parles. :trollface:

**Comment by bloodyowl** [comment]
hop: nouveau doodle http://doodle.com/poll/xky9if3dwb9zh3nh

**Comment by bloodyowl** [comment]
resheduled pour le Lundi 7 Mars. À vos PR les cocos ✨📝 https://github.com/TablesRondes/tables-rondes/blob/master/08-JavaScript-Fatigue.md
