### ISSUE TITLE
next

### ISSUE THREAD

**Issue by bloodyowl** [TablesRondes/tables-rondes#69]
petite issue pour commencer à chercher un sujet intéressant pour la prochaine édition.

pistes possibles:

- design tools (sketch, origami, style guides …)
- outils de typage js (typescript, flow)
- architectures d'app (relay, redux, flux)

proposez vos idées 😃

**Comment by MattiSG** [comment]
À partir de quand vanilla ne suffit plus ?

**Comment by revolunet** [comment]
- bonnes pratiques pour faire des components react réutilisables et distribuables
 - meilleurs boilerplates/tools pour produire des composants à la pelle
 - documentation : composants (proptypes, css...), styleguides css

**Comment by risseraka** [comment]
Vers la fin des backends avec les bases cloud et les services lambda ?

**Comment by bloodyowl** [comment]
## design tools (sketch, origami, style guides …)

**Comment by bloodyowl** [comment]
## outils de typage js (typescript, flow)

**Comment by bloodyowl** [comment]
## architectures d'app (relay, redux, flux)

**Comment by bloodyowl** [comment]
## À partir de quand vanilla ne suffit plus ?

**Comment by bloodyowl** [comment]
## bonnes pratiques pour faire des components react réutilisables et distribuables

**Comment by bloodyowl** [comment]
## meilleurs boilerplates/tools pour produire des composants à la pelle

**Comment by bloodyowl** [comment]
## documentation : composants (proptypes, css...), styleguides css

**Comment by bloodyowl** [comment]
## Vers la fin des backends avec les bases cloud et les services lambda ?

**Comment by bloodyowl** [comment]
Upvotez sur les propositions qui vous intéressent le plus 👍

**Comment by bloodyowl** [comment]
Le peuple a parlé, du coup ce sera **à partir de quand vanilla ne suffit plus ?**

Pour préparer et structurer un peu la table ronde: quelles sont vos éventuelles questions sur ce thème ?

**Comment by kud** [comment]
- Est-ce en rapport avec le nombre d'intervenants sur un projet ?
- Quel framework pour quel besoin ?
- Peut-on facilement revenir d'un framework vers vanilla si besoin ?
- Quel est le coût de tout de même continuer en vanilla ?

**Comment by MattiSG** [comment]
- Comment estimer la complexité vers laquelle tendra une base de code quand on l'initie ?
- Quel sous-ensemble de JS est suffisamment bien supporté en cross-browser pour être utilisable sans surcouche ?
- Où est la limite de Vanilla quand on sait qu'on va forcément faire émerger des helpers ?

**Comment by bloodyowl** [comment]
http://doodle.com/poll/ga9yfhmpzt383g46

**Comment by bloodyowl** [comment]
Du coup, Altima nous prête gentiment une salle pour le 28.

@kud @MattiSG @revolunet @clementgalidie @arnaudlimbourg @Freddy03h @skinnyfoetusboy @remitbri @risseraka à vos PR si vous pouvez venir 😄

**Comment by bloodyowl** [comment]
bon bah si personne s'inscrit, on reporte 🙃

**Comment by clementgalidie** [comment]
Sympa Altima. :smirk:

Peut-être attendre la fin de ce week-end, voire lundi en fin de matinée, avant de reporter, nan ?
